import {initializeApp} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-app.js";
import {getAuth,onAuthStateChanged,setPersistence,browserLocalPersistence,signInWithEmailAndPassword,signOut} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-auth.js";
import {getFirestore,doc,onSnapshot,setDoc,serverTimestamp,getDoc} from "https://www.gstatic.com/firebasejs/12.18.0/firebase-firestore.js";
const firebaseConfig={apiKey:"AIzaSyASl5jV5mLaDh8CoeeofV7ftVJ3gaog64E",authDomain:"karwa0.firebaseapp.com",projectId:"karwa0",storageBucket:"karwa0.firebasestorage.app",messagingSenderId:"485451054622",appId:"1:485451054622:web:ce9b0e2ff2280870a8780f"};
const app=initializeApp(firebaseConfig,"karwa-services-portal-v3"),auth=getAuth(app),db=getFirestore(app);try{await setPersistence(auth,browserLocalPersistence)}catch{}
const $=id=>document.getElementById(id), views=["authView","applicationView","providerView","deniedView"];let user=null,userData=null,gps=null,meals=[],providerGps=null,providerMeals=[],unsubs=[];
function show(id){views.forEach(v=>$(v)?.classList.toggle("hidden",v!==id))}function toast(t){$("toast").textContent=t;$("toast").classList.add("show");setTimeout(()=>$("toast").classList.remove("show"),2600)}function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]))}function money(n){return Number(n||0).toLocaleString("ar-IQ")+" د.ع"}function clear(){unsubs.forEach(f=>f?.());unsubs=[]}
function renderMeals(hostId,countId,list,editable=true){$(countId).textContent=`${list.length} وجبة`;$(hostId).innerHTML=list.length?list.map((m,i)=>`<div class="meal"><div><b>${esc(m.name)}</b><small>${esc(m.description||"بدون تفاصيل")}</small></div><span class="price">${money(m.price)}</span>${editable?`<button type="button" class="btn danger" data-rm="${i}">حذف</button>`:""}</div>`).join(""):`<small style="color:#6b7b91">لا توجد وجبات مضافة.</small>`;if(editable)$(hostId).querySelectorAll("[data-rm]").forEach(b=>b.onclick=()=>{list.splice(+b.dataset.rm,1);renderMeals(hostId,countId,list,editable);if(hostId==="pMealList")preview()})}
function addMeal(prefix,list,host,count){const n=$(prefix+"MealName").value.trim(),p=Number($(prefix+"MealPrice").value),d=$(prefix+"MealDesc").value.trim();if(!n||!Number.isFinite(p)||p<=0)return toast("أدخل اسم الوجبة وسعرًا صحيحًا");if(list.length>=30)return toast("الحد الأقصى 30 وجبة");list.push({name:n,price:Math.round(p),description:d});["MealName","MealPrice","MealDesc"].forEach(x=>$(prefix+x).value="");renderMeals(host,count,list,true);if(prefix==="p")preview()}
$("addMeal").onclick=()=>addMeal("",meals,"mealList","mealCount");$("pAddMeal").onclick=()=>addMeal("p",providerMeals,"pMealList","pMealCount");
function locate(target){if(!navigator.geolocation)return toast("GPS غير مدعوم");navigator.geolocation.getCurrentPosition(p=>{const x={latitude:p.coords.latitude,longitude:p.coords.longitude,accuracy:p.coords.accuracy};if(target==="app"){gps=x;$("gpsStatus").textContent=`تم التحديد ✓ ${x.latitude.toFixed(5)}, ${x.longitude.toFixed(5)}`}else{providerGps=x;$("pGpsStatus").textContent=`تم التحديث ✓ ${x.latitude.toFixed(5)}, ${x.longitude.toFixed(5)}`}toast("تم تحديد الموقع")},()=>toast("تعذر الوصول إلى GPS. اسمح للموقع باستخدام موقعك."),{enableHighAccuracy:true,timeout:12000})}
$("gpsBtn").onclick=()=>locate("app");$("pGpsBtn").onclick=()=>locate("provider");
$("loginBtn").onclick=async()=>{try{await signInWithEmailAndPassword(auth,$("loginEmail").value.trim(),$("loginPassword").value)}catch{toast("تعذر تسجيل الدخول. تحقق من البريد وكلمة المرور")}};$("logoutBtn").onclick=()=>signOut(auth);$("deniedLogout").onclick=()=>signOut(auth);
function applicationState(a){const s=a?.status||"new",chip=$("applicationStatus"),notice=$("applicationNotice"),btn=$("submitApplication");chip.className="status";notice.className="notice hidden";btn.disabled=false;btn.textContent="إرسال طلب الاعتماد للإدارة";$("heroStatus").textContent="طلب جديد";if(s==="pending"){chip.textContent="قيد المراجعة";$("heroStatus").textContent="بانتظار موافقة الإدارة";notice.className="notice";notice.textContent="تم استلام طلبك بنجاح. لا يمكن الدخول إلى لوحة الخدمات قبل موافقة الإدارة.";btn.disabled=true;btn.textContent="الطلب قيد المراجعة"}else if(s==="rejected"){chip.className="status bad";chip.textContent="يحتاج تعديلًا";$("heroStatus").textContent="مطلوب تعديل البيانات";notice.className="notice bad";notice.textContent=a.reviewNote||"راجع البيانات وأعد إرسال الطلب.";btn.textContent="إعادة إرسال الطلب"}else{chip.textContent="جديد"}}
async function openApplicant(){show("applicationView");const [a,r]=await Promise.all([getDoc(doc(db,"driverApplications",user.uid)),getDoc(doc(db,"restaurants",user.uid))]);if(a.exists()){const d=a.data();$("ownerName").value=d.name||userData?.name||"";$("ownerPhone").value=d.phone||"";$("city").value=d.city||"الموصل";applicationState(d)}else{$("ownerName").value=userData?.name||user.displayName||"";applicationState(null)}if(r.exists()){const d=r.data();$("restaurantName").value=d.name||"";$("restaurantPhone").value=d.phone||"";$("restaurantAddress").value=d.address||"";gps=d.location||null;meals=Array.isArray(d.meals)?d.meals.map(x=>({...x})):[];if(gps)$("gpsStatus").textContent=`محفوظ ✓ ${Number(gps.latitude).toFixed(5)}, ${Number(gps.longitude).toFixed(5)}`;renderMeals("mealList","mealCount",meals,true)}else renderMeals("mealList","mealCount",meals,true);const u=onSnapshot(doc(db,"driverApplications",user.uid),s=>applicationState(s.exists()?s.data():null));unsubs.push(u)}
$("applicationForm").onsubmit=async e=>{e.preventDefault();const owner=$("ownerName").value.trim(),phone=$("ownerPhone").value.trim(),rn=$("restaurantName").value.trim(),rp=$("restaurantPhone").value.trim(),ra=$("restaurantAddress").value.trim();if(owner.length<2||phone.replace(/\D/g,"").length<8||rn.length<2||rp.replace(/\D/g,"").length<8||ra.length<3)return toast("أكمل البيانات المطلوبة بشكل صحيح");if(!gps)return toast("حدد موقع المطعم GPS");if(!meals.length)return toast("أضف وجبة واحدة على الأقل");try{await setDoc(doc(db,"driverApplications",user.uid),{userId:user.uid,name:owner,email:user.email||"",phone,serviceType:"other",vehicleType:"",vehicleMake:"",vehicleModel:"",vehicleCondition:"",plate:"",city:$("city").value,status:"pending",submittedAt:serverTimestamp(),updatedAt:serverTimestamp()},{merge:true});await setDoc(doc(db,"restaurants",user.uid),{ownerId:user.uid,name:rn,address:ra,phone:rp,location:gps,meals:meals.map(x=>({...x})),active:false,approvalStatus:"pending",updatedAt:serverTimestamp(),createdAt:serverTimestamp()},{merge:true});toast("تم إرسال الطلب إلى الإدارة للموافقة")}catch(e){console.error(e);toast("تعذر إرسال الطلب. تأكد من نشر Firestore Rules المرفقة")}};
function preview(){$("previewName").textContent=$("pName").value||"مطعمك";$("previewAddress").textContent=$("pAddress").value||"العنوان";$("previewPhone").textContent=$("pPhone").value||"الهاتف";$("previewMeals").innerHTML=providerMeals.slice(0,4).map(m=>`<div class="meal"><div><b>${esc(m.name)}</b><small>${esc(m.description||"")}</small></div><span class="price">${money(m.price)}</span></div>`).join("")}
async function openProvider(){show("providerView");const snap=await getDoc(doc(db,"restaurants",user.uid));if(!snap.exists())return toast("ملف المطعم غير موجود. راجع الإدارة");const d=snap.data();$("pName").value=d.name||"";$("pPhone").value=d.phone||"";$("pAddress").value=d.address||"";providerGps=d.location||null;providerMeals=Array.isArray(d.meals)?d.meals.map(x=>({...x})):[];$("activeMetric").textContent=d.active===false?"متوقف":"نشط";$("mealsMetric").textContent=providerMeals.length;if(providerGps)$("pGpsStatus").textContent=`${Number(providerGps.latitude).toFixed(5)}, ${Number(providerGps.longitude).toFixed(5)}`;renderMeals("pMealList","pMealCount",providerMeals,true);preview();["pName","pPhone","pAddress"].forEach(id=>$(id).oninput=preview);const u=onSnapshot(doc(db,"restaurants",user.uid),s=>{if(s.exists()){$("activeMetric").textContent=s.data().active===false?"متوقف":"نشط"}});unsubs.push(u)}
$("providerForm").onsubmit=async e=>{e.preventDefault();if(!providerGps)return toast("حدد موقع المطعم");if(!providerMeals.length)return toast("يجب وجود وجبة واحدة على الأقل");try{await setDoc(doc(db,"restaurants",user.uid),{ownerId:user.uid,name:$("pName").value.trim(),phone:$("pPhone").value.trim(),address:$("pAddress").value.trim(),location:providerGps,meals:providerMeals.map(x=>({...x})),updatedAt:serverTimestamp()},{merge:true});$("mealsMetric").textContent=providerMeals.length;toast("تم حفظ التغييرات وظهورها للعملاء")}catch(e){console.error(e);toast("تعذر حفظ التغييرات")}};
onAuthStateChanged(auth,async u=>{clear();user=u;$("logoutBtn").classList.toggle("hidden",!u);if(!u){$("accountName").textContent="";show("authView");return}try{const s=await getDoc(doc(db,"users",u.uid));if(!s.exists())throw new Error("NO_PROFILE");userData=s.data();$("accountName").textContent=userData.name||u.email||"";if(userData.role==="serviceProvider")await openProvider();else if(userData.role==="serviceApplicant")await openApplicant();else{$("deniedText").textContent=userData.role==="customer"?"هذا حساب عميل، وصفحة الخدمات الأخرى مخصصة لمزودي الخدمات.":userData.role?.startsWith("driver")?"هذا حساب كابتن، استخدم صفحة الكابتن.":"هذا الحساب غير مخصص لبوابة الخدمات الأخرى.";show("deniedView")}}catch(e){console.error(e);toast("تعذر قراءة صلاحية الحساب")}});
